community/plugins.html

Moving to go-maven-poller repo of @aresok. See: ThoughtWorksInc/go-maven-poller#10.

Change ownership of go-maven-poller

---

community/plugins.html

Added a new section to the plugins page to highlight enterprise extensions

added enterprise extensions area

---

community/plugins.html

Adding reference to websocket notifier plugin to new notifications plugin section

Adding reference to websocket notifier plugin 

---

community/plugins.html

My contribution to the Go plugin challenge.

Addition of Cloud Foundry polling plugin

---

community/plugins.html

Email notification plugin

---

_config.yml
_includes/header.html
css/main.css
css/responsive.css

Change support header to be a little header instead of a link

---

community/plugins.html

Hope this is within the plugin competition time limit :)

Adding docker task

---

community/plugins.html

Hope its not too late yet for the Plugin challenge PRs :smile:

Build Github Pull Request - SCM Plugin

---

community/plugins.html

Updating the download links from Snap-CI to Github Releases

---

community/plugins.html

* Removed the older, no longer supported Artifactory poller.
* Added an Artifactory poller and a generic artifactory poller in the listing

Changed the Artifactory plugin in the listing.

---

_layouts/post.html

Added a button that will allow people to easily tweet our blog posts. Totally up for someone deciding the button should be in a different place.

added tweet button

---

_includes/releaseAnnouncement.html

Merge this when the installer and release notes are out

15.1 Release announcement banner on go.cd homepage

---

_posts/2015-05-07-go-webinar-recording.markdown

new webinar

---

_posts/2015-06-13-using-windows-powershell-tasks.markdown

Added a post that gives some background\preparation for running PowerShell tasks on a Go Agent
Added some content on propogating errors within a PowerShell script

Added a Windows PowerShell blog post

---

_posts/2015-06-23-hardly-anyone-knows-cd.markdown

Trying this again, the first try didn't get committed correctly for some reason.
Open to comments / proofreading if people have cycles.

new blog post

---

community/plugins.html

Added material plugin s3 poller to plugins list

---

releases/in-progress.html
releases/index.html

Reverts gocd/gocd.github.io#182

Revert "Update release notes for 15.2"

---

_includes/releaseAnnouncement.html
index.html

Reverts gocd/gocd.github.io#180

Revert "Bump version number on home page."

---

_includes/releaseAnnouncement.html
index.html

Reverts gocd/gocd.github.io#185

Bump version number on home page.

---

_data/task_plugins.yml

Hi,
I've build a [Gradle plugin](https://jmnarloch.wordpress.com/2015/09/05/go-continuous-delivery-gradle-task/) for Go and I would like to leave here a info, if you don't mind.

gocd-gradle-plugin

---

_layouts/home.html

This prevents mixed content warnings along as well as updates the links that allow https to that.
Also indented this correctly.

Update to use https where possible

---

_data/tools.yml
community/plugins.html

Enlisting GoCD Janitor against the tools section

Adding new section - Tools as suggested by Ketan

---

community/plugins.html

@ketan Sorry I forgot this in the last PR.

Adding clear:both so the Tools comes over at the next line

---

_data/tools.yml

Updating the description on the GoCD Janitor tool

---

_data/task_plugins.yml

Hi,
I've created a additional SBT task plugin for go cd: https://github.com/jmnarloch/gocd-sbt-plugin

gocd-sbt-plugin

---

_data/task_plugins.yml

new plugin gallery item for SonarQube quality gate plugin

added sonarqube quality gate plugin

---

download/index.html
getting-started/part-3.md
js/download.js

For @ketan to take a look and merge. I'm fine with #250. Thought I'd save you some time by toggling it to the right one. [This](https://github.com/gocd/gocd.github.io/commit/cc398c75d94853d95ce52795e8a060358a8862d8) is the commit which does that.
Also, had a [small change](https://github.com/gocd/gocd.github.io/commit/148f6bf41ea7166c40737c4338093fea118711bf) that I needed to make to a getting started page.

PR #250 with toggle and some duplication removed

---

_includes/releaseAnnouncement.html
releases/index.html

Release notes of 16.2

---

community/partners.markdown

As suggested by @kmugrage a while ago :)

Add Skelton Thatcher as a Consulting Partner

---

_data/task_plugins.yml

Added Go Slack Task plugin to plugins page.

Add Go Slack Task plugin

---

_data/auth_plugins.yml

Ddded an entry for the authentication plugin I published.

Added strong auth plugin to list.

---

source/feed.xml.builder
source/posts/2014-02-24-build-promotion-go.html.markdown.erb
source/posts/2014-02-24-deploy-package-not-just-tag-branch-or-binary.html.markdown.erb
source/posts/2014-02-24-go-template-permissions.html.markdown.erb
source/posts/2014-02-24-how-implement-continuous-delivery-enterprise-java-middleware.html.markdown.erb
source/posts/2014-02-24-how-peg-your-pipeline-dependency-version.html.markdown.erb
source/posts/2014-02-24-model-everything-fail-fast.html.markdown.erb
source/posts/2014-02-24-tracing-our-path-production.html.markdown.erb
source/posts/2014-02-25-go-moving-to-open-source.html.markdown.erb
source/posts/2014-02-25-why-we-need-to-practice-cd.html.markdown.erb
source/posts/2014-04-24-Go_14_1_announced.html.markdown.erb
source/posts/2014-04-24-agent-bootstrapper-upgrade-for-plugins.html.markdown.erb
source/posts/2014-04-24-source-code-for-go-now-available.html.markdown.erb
source/posts/2015-06-18-authentication-end-point.html.markdown.erb
source/posts/2015-06-18-plugin-settings.html.markdown.erb

Individual commits have messages.

Change blog times

---

data/auth_plugins.yml
data/task_plugins.yml

Fixes issue mentioned [here](https://github.com/gocd/www.go.cd/pull/257#issuecomment-216621049).

Add missing plugins from old site

---

data/task_plugins.yml

Adding the plugin metadata as requested in https://groups.google.com/forum/#!topic/go-cd/Jd-DBeONP1o

add Scalastyle Github Pull Request plugin to the list of task plugins

---

source/posts/2016-07-13-DotNet-Core-and-GoCD.html.markdown.erb

Blog - copy change and added banner image

Blog - copy change and added banner image

---

data/events.yml

Updated list of events - Devops days

Updated list of events - Devops days

---

data/events.yml

Minor spelling edits

---

config.rb
source/partials/release_notes/_release-16-7-0.html.erb

* Surround git shas with `<code/>`
* Changed curly quotes with simple quotes
* Changed api urls to https

Minor improvements to release notes.

---

data/events.yml

Edit "November"

---

source/index.html.erb

Removed #support from the free trial URL

Removed #support from the free trial URL

---

source/assets/javascripts/app/_download.js

Use a comparator for sort go version numbers

---

source/partials/_header.erb

Added support link to the header

Added support link to the header

---

source/posts/2014-05-18-manage-agents-with-docker.html.markdown.erb

Updated the link on the post

---

source/index.html.erb

Changed the headline and sub-captions

Changed the headline and sub-captions

---

data/scm_plugins.yml

I want to share my little plugin with you :smile:

added plugin: Artifactory SCM

---

data/webinars.yml

Updated webinars for Q4 2016

---

data/elastic_agent_plugins.yml
source/plugins.html.erb

New category added for elastic agent plugins

New category added for elastic agent plugins

---

config.rb

Added right TPTM URL

---

source/index.html.erb

Added back the support link to Free trial link

Added back the support link to Free trial link

---

source/download.html.erb

Download page to new support link

Download page to new support link

---

config.rb
lib/tasks/static_checks.rake

Added URL for recode podcast

---

source/partials/release_notes/_release-16-12-0.md.erb

Lists all the PRs submitted to upgrade plugins to make them work with 17.1

Update release notes about plugin upgrades

---

config.rb
lib/tasks/static_checks.rake

Added twiet URL and updated recode URL

Added twiet URL and updated recode URL

---

data/auth_plugins.yml

Add guest login auth plugin to list

---

source/why-gocd.html.erb

Removed the 2016 Roadmap section

Removed the 2016 Roadmap section

---

source/assets/stylesheets/scss/_campaign.scss
source/assets/stylesheets/site.css.scss
source/campaignpages/demo.html.markdown.erb
source/index.html.erb
source/layouts/campaignlanding.erb
source/partials/_supportbanner.erb
source/partials/_whygocdfeature1.erb
source/partials/_whygocdfeature2.erb
source/partials/_whygocdfeature3.erb

Layout for Campaign Landing pages done
Demo page with dummy content created for review
Modified homepage to extract sections as partials and reused the same in campaign pages

Campaign landing pages

---

source/partials/next_release/_release.md.erb

Description for config save optimisation

---

source/partials/release_notes/_release-16-4-0.html.erb
source/partials/release_notes/_release-16-5-0.html.erb

Changed Jen's github ID

---

data/paid_plugins.yml

Altered CTA for paid plugins

---

source/assets/images/Go_watermark_logo.svg
source/assets/images/icons/go.cd_security.svg
source/assets/stylesheets/scss/_contribute.scss
source/assets/stylesheets/scss/_getting-started.scss
source/contribute.html.erb
source/partials/release_notes/_release-16-12-0.md.erb
source/partials/release_notes/_release-17-1-0.md.erb

Added Security section under contribute page
Fixed bug #285 
Fixed the duplicate ID in release notes bug

Added Security section under contribute

---

source/assets/stylesheets/scss/_contribute.scss
source/contribute.html.erb

Fixed issue in tablet/mobile view

Design feedback implemented in contribute page

---

data/events.yml
source/events.html.erb
source/posts/2015-11-09-deserialization-vulnerability-commons-collections.html.markdown.erb

Removed Snap ref on events page
Updated event list

Events update

---

data/events.yml
source/events.html.erb

Adjusted space and removed copy

Events Page Copy

---

source/posts/2017-02-16-migrating-snapci-to-gocd.html.markdown.erb

Adding SnapCI Migration Post

---

source/partials/_analytics.html.erb

Added twitter analytic code

---

data/paid_plugins.yml

Added ECS Elastic agent plugin in paid plugin section

Added ECS Elastic agent plugin

---

source/assets/stylesheets/scss/_campaign.scss
source/campaign/index.html.erb
source/layouts/campaignlanding.erb
source/partials/chef/_chef-feature1.erb
source/partials/chef/_chef-feature2.erb
source/partials/chef/_chef-feature3.erb

fix for campaign landing page and blog style

Campaign landing page

---

source/blog.html.erb
source/layouts/post.erb

This can be reverted back to make blog subscribe visible again.

Removed blog subscribe temporarily

---

data/notification_plugins.yml

By advice of @ketan on https://github.com/gocd/www.go.cd/pull/504, I've updated my plugin description. Thanks!

Update my plugin description

---

data/task_plugins.yml

Artifactory Plugin publish

---

source/posts/2017-06-13-modeling-deployment-pipelines-agents-environments.html.markdown.erb

Publishing Part 6

---

data/notification_plugins.yml

I wrote a notification plugin recently, and have modified notification_plugins.yml to contain its link and description. Please consider this PR for publication on your web site.

Added notification plugin for AWS SNS (Simple Notification Service)

---

source/assets/stylesheets/scss/_blog.scss
source/assets/stylesheets/scss/_general.scss
source/assets/stylesheets/scss/_subscribe.scss
source/blog.html.erb
source/partials/_latest_blog_post_summary.html.erb
source/partials/_subscribe_to_blog.html.erb

Getting back @naveen's changes which was accidentally reverted by nuyday

Latest blog design / subscribe to post design changes

---

data/authorization_plugins.yml

Hi,
has anyone checked the plugin?

Added Crowd Authentication plugin references

---

data/scm_plugins.yml

Added entry for Phabricator Staging Area Material plugin.

Add Phabricator Staging Area Material plugin info

---

source/posts/2017-07-18-continuous-deployment-strategies.html.markdown.erb
source/posts/2017-07-20-deployment-pipeline-automated-testing.html.markdown.erb

Added link for CD101 series

---

source/posts/2017-07-13-introduction-continuous-delivery-101.html.markdown.erb
source/posts/2017-07-20-deployment-pipeline-automated-testing.html.markdown.erb

altered URL format

---

source/posts/2017-07-13-introduction-continuous-delivery-101.html.markdown.erb

- since this was failing in live

removed the advance URL

---

source/partials/_analytics.html.erb
source/partials/_post-page_subscribe_to_blog.html.erb
source/partials/_subscribe_to_blog.html.erb
source/sales-sign-up.html.erb
source/subscribe.html.erb

* Also, show a message if the marketo form/content fails to load.
* Even though async="true" feels weird, it works and keep the proper HTML check happy.

Load Marketo content async

---

source/elastic-agents/index.html.erb
source/partials/release_notes/_release-17-8-0.md.erb
source/posts/2017-08-01-gocd-elastic-agents.html.markdown.erb

ECS copy edits

---

source/elastic-agents/index.html.erb

See: https://www.w3.org/QA/Tips/noClickHere

Remove click-here

---

data/tag_page_header_info.yml
source/posts/tag.html.erb

Tag pages are generated. No direct way to set the title, description, keywords. So, need to do this.
@nyuday needed this.

Allow header changes in tag pages

---

source/glossary/index.html.erb
source/robots.txt.erb

- added glossary page
- removed jenkins and cd101 from robots.txt
- added glossary to robots.txt

Added Glossary page (draft)

---

source/partials/release_notes/_release-17-10-0.md.erb

Add release notes for v17.10.0

---

data/authorization_plugins.yml
source/partials/release_notes/_release-18-1-0.md.erb

* List Guest Login Plugin under authorization plugins
* Add link to job feed api

Fix release notes 18.1.0

---

data/task_plugins.yml

Add missing author_name and fix releases_url key.

Fix plugin listing.

---

_posts/2016-03-21-your-first-pipeline.markdown

Hi, this my first attempt at a guest post, so please be gentle. Feedback of all kinds very welcome.

Guest post: Your first Pipeline with GoCD

---

source/posts/2018-03-21-continuous-delivery-gocd-kubernetes.html.markdown.erb

Renamed the file to match the date. 
Added the rights docs link. Removed draft mode.

k8edit - final touches

---

data/tag_page_header_info.yml
source/contributor-license-agreement.html.erb
source/elastic-agents/index.html.erb
source/getting-started/part-1.html.erb
source/partials/release_notes/_release-16-10-0.html.erb
source/partials/release_notes/_release-16-11-0.html.erb
source/partials/release_notes/_release-16-5-0.html.erb
source/partials/release_notes/_release-16-6-0.html.erb
source/partials/release_notes/_release-16-7-0.html.erb
source/partials/release_notes/_release-16-8-0.html.erb
source/partials/release_notes/_release-16-9-0.html.erb
source/partials/release_notes/_release-17-11-0.md.erb
source/partials/release_notes/_release-17-12-0.md.erb
source/partials/release_notes/_release-17-5-0.md.erb
source/partials/release_notes/_release-17-6-0.md.erb
source/posts/2014-05-18-manage-agents-with-docker.html.markdown.erb
source/posts/2015-09-01-visibility-is-opportunity.html.markdown.erb
source/posts/2016-07-13-DotNet-Core-and-GoCD.html.markdown.erb
source/posts/2017-03-01-importance-and-principles-of-cd-pipelines.html.markdown.erb
source/posts/2017-04-06-reusing-pipelines.html.markdown.erb
source/posts/2017-04-17-build-propagation-using-fan-in-fan-out.html.markdown.erb
source/posts/2017-06-20-hotfixes-rollback-rollforward.html.markdown.erb
source/posts/2018-02-13-managing-build-versions-pipeline.html.markdown.erb

OK to fix the spelling and trailing white space ?

Propose fix typos

---

source/assets/stylesheets/scss/_homepage.scss
source/index.html.erb

Homepage webinar promo

---

source/download.html.erb

as mentioned on #767 and briefly discussed with @arvindsv on gitter.

fix #767 - broken link on download page

---

source/analytics/index.html.erb
source/download.html.erb
source/enterprise-campaign/index.html.erb
source/enterprise.html.erb
source/enterprise/contact.html.erb
source/enterprise/pricing.html.erb
source/enterprise/support.html.erb
source/partials/_post-page_subscribe_to_blog.html.erb
source/partials/_subscribe_to_blog.html.erb
source/sales-sign-up.html.erb
source/subscribe.html.erb

- Ensure marketo_popover.js loads before marketo external js (use defer to ensure order without blocking load)
- Remove unused/obsolete references to marketo_popover.js

Try to eliminate Marketo load error on first nav

---

source/enterprise/support.html.erb

https://www.linkedin.com/in/vijay-mohan-b965b239/

changed BarclayCards to Barclaycard in bio

---

data/plugins/paid_plugins.yml

* Change contact and readmore urls to point to the new enterprise page.

Add analytics plugin to the paid section in the plugins page.

---

data/plugins/repo_plugins.yml
data/plugins/task_plugins.yml

Added entries for plugins from kszatan/gocd-b2-artifacts repository.

Add gocd-b2-artifacts plugins entries

---

source/assets/javascripts/marketo_popover.js
source/assets/stylesheets/scss/_subscribe.scss
source/download.html.erb
source/partials/_post-page_subscribe_to_blog.html.erb
source/partials/_subscribe_to_blog.html.erb
source/sales-sign-up.html.erb
source/subscribe.html.erb

GDPR double opt-in confirmation

---

source/assets/stylesheets/enterprise/_contact.scss
source/assets/stylesheets/enterprise/_support.scss

Removing the floating checkbox red border from the enterprise contact and support pages

GDPR enterprise page styling fixes

---

data/events.yml

added upcoming events to the page

added new events

---

data/plugins/artifact_plugins.yml

Small change: since this work was done in my company work time and with help from some colleagues, it makes more sense to change the author to the company instead of myself :-)

Update artifact_plugins.yml (change author and page)

---

source/assets/images/help/community.svg
source/assets/images/help/docs.svg
source/assets/images/help/intro.svg
source/assets/stylesheets/scss/_help.scss
source/help.html.erb
source/partials/_header.erb

• Updated copy
• Removed some items
• Updated svg illustrations

Changes to Help page

---

source/assets/stylesheets/enterprise/_overview.scss
source/assets/stylesheets/enterprise/_utilities.scss
source/assets/stylesheets/scss/_blog.scss
source/assets/stylesheets/scss/_general.scss
source/assets/stylesheets/scss/_gocd-demo.scss
source/assets/stylesheets/site.css.scss
source/interactive-gocd/index.html.erb

Interactive gocd

---

source/assets/stylesheets/scss/_downloads.scss

Revert "[WIP] Remove additional padding on windows tab when there is no 32-bit and 64-bit info to show."

---

source/analytics-trial/index.html.erb
source/assets/stylesheets/components/_cornered-banner.scss
source/assets/stylesheets/scss/_analytics-trial.scss
source/assets/stylesheets/scss/_blog.scss
source/assets/stylesheets/site.css.scss
source/posts/2019-01-14-cd-metrics-deployment-lead-time.html.markdown.erb

Completion of analytics trial page

Analytics trail

---

source/partials/next_release/_release.md.erb
source/partials/release_notes/_release-19-3-0.md.erb

* Added removal of ElasticAgent Profile V1 under breaking change
section.

Minor tweaks to the release notes

---

source/assets/stylesheets/scss/_test-drive-gocd.scss

Dialed in the spacing in the headers to improve display across screen sizes. Also updated some very minor text styles.

Update Test Drive scss

---

source/assets/stylesheets/scss/_releases.scss
source/partials/release_notes/_release-19-3-0.md.erb

- This is added in favor of the issue https://github.com/gocd/gocd/issues/6328

Add upgrade instruction in 19.3.0 release note

---

source/assets/stylesheets/scss/_blog.scss
source/posts/2019-06-25-GoCD-non-root-containers.html.markdown.erb

Needs to be merged at the time of 19.6.0 release.

Running GoCD containers as non root, blog post

---

source/posts/2019-06-25-GoCD-non-root-containers.html.markdown.erb

Non root GoCD container blog post, add shared volume permissions section

---

source/assets/stylesheets/components/_cornered-banner.scss
source/assets/stylesheets/scss/_blog.scss
source/jenkins/index.html.erb
source/posts/2016-01-17-not-done-unless-its-done.html.markdown.erb
source/posts/2016-02-08-not-done-unless-its-done-security.html.markdown.erb
source/posts/2016-06-08-Add-performance-testing-to-your-Continuous-Delivery-pipeline.html.markdown.erb
source/posts/2017-04-25-gocd-over-jenkins.html.markdown.erb
source/posts/2017-06-22-deployment-pipeline-patterns-infographic.html.markdown.erb
source/posts/2017-07-10-gocd-vs-spinnaker.html.markdown.erb
source/posts/2017-07-13-introduction-continuous-delivery-101.html.markdown.erb
source/posts/2017-07-20-deployment-pipeline-automated-testing.html.markdown.erb
source/posts/2017-08-22-principles-practices-continuous-delivery.html.markdown.erb
source/posts/2017-09-12-value-stream-mapping.html.markdown.erb
source/posts/2017-10-03-introduction-continuous-delivery-deployment-tools.html.markdown.erb
source/posts/2018-01-17-continuous-delivery-beginners-guide.html.markdown.erb
source/posts/2018-07-17-gocd-materials-blacklisting-whitelisting.html.markdown.erb
source/posts/2018-08-21-replacing-gocd-with-gocd.html.markdown.erb
source/posts/2018-10-16-new-gocd-features.html.markdown.erb
source/why-gocd.html.erb

The initial implementation was too restrictive and didn't fully take advantage of flexbox. The partial has been refactored to be more flexible and properly resize the containers and elements based on the content.

Cornered blog banners, Initial refactor

---

source/assets/stylesheets/scss/_footer.scss
source/assets/stylesheets/scss/_gdpr.scss

Moved GDPR banner to the bottom of the browser window, added border top color as well.
Reduced z-index for footer by 1px and made GDPR section z-index to 100

Moved GDPR banner to bottom of browser window

---

source/partials/next_release/_release.md.erb

Added mention of `Pipeline config API v8` in API improvement section of next-release, release notes.

Release notes for 19.6

---

source/assets/javascripts/app/_download.js
source/download.html.erb

Add release date to downloads (#963)

---

source/partials/release_notes/_release-19-6-0.md.erb
source/partials/release_notes/_release-19-7-0.md.erb

Merge only after 19.8.0 release

 add warnings for fresh install using windows installers

---

source/partials/next_release/_release.md.erb
source/partials/release_notes/_release-19-8-0.md.erb

Adding release notes for 19.8.0

Add release notes for 19.8.0

---

source/assets/stylesheets/scss/_releases.scss
source/releases.html.erb

release notes: make the release versions section scrollable

---

source/assets/stylesheets/components/_flex-item.scss
source/assets/stylesheets/scss/_getting-started.scss
source/assets/stylesheets/scss/_test-drive-gocd.scss
source/getting-started/_getting-started-nav.erb
source/getting-started/part-1.html.erb
source/getting-started/part-2.html.erb
source/getting-started/part-3.html.erb
source/test-drive-gocd/index.html.erb

Getting Started page and Test Drive Gocd Modules Refactoring.
a) Avoided Nested Loops 
b) Implemented Grid Layout
c) Following BEM for Class Names.

Refactoring: Getting Started and Test drive Gocd Pages

---

source/partials/release_notes/_release-19-11-0.md.erb

Mention environment variable from environment issue on 19.11.0 release notes

---

source/partials/release_notes/_release-19-11-0.md.erb

Update 19.11.0 release notes to reword as per 19.12.0 release.

---

data/plugins/elastic_agent_plugins.yml

This PR adds listing of elastic agent plugin for AWS EC2.

Aws ec2 plugin

---

source/test-drive-gocd/try.sh

Fix try.sh error

---

source/download.html.erb

We keep sharing the link anyway ...

Add link to unsupported releases

---

data/plugins/authorization_plugins.yml
data/plugins/elastic_agent_plugins.yml

Add newly opensourced Azure and ECS elastic agent, LDAP authorization plugin to the plugin list

Add newly open-sourced plugins

---

source/download.html.erb

Update helm commands for k8s instructions

---

data/plugins/authorization_plugins.yml
source/plugins.html.erb

Make it more clear that plugins might be un-maintained.

Update plugin page description

---

source/partials/release_notes/_release-20-7-0.md.erb

release notes for 20.7.0
Preview: https://gocd.github.io/pr-review.gocd.org/pr-1160/releases/

Add release notes for 20.7.0

---

source/partials/release_notes/_release-20-10-0.md.erb

Added release notes for GoCD release- 20.10.0

GoCD 20.10.0 release notes

---

data/plugins/task_plugins.yml

This PR adds the new CMake task plugin to the list of task plugins.

Add CMake Task plugin

---

.github/workflows/pr_workflow.yml
lib/tasks/static_checks.rake

Updating to github actions

---

.github/workflows/build_and_preview.yml

- add workflow to build and deploy to preview

Update github actions

---

data/plugins/analytics_plugins.yml
source/plugins.html.erb

Adding the open-sourced plugin to the plugins page

Add analytics plugin on the plugin pages

---

source/download.html.erb
source/partials/release_notes/_release-22-1-0.md.erb

See https://github.com/gocd/gocd/issues/10285

Add release notes for 22.1.0

---

source/partials/release_notes/_release-22-2-0.md.erb

Just a draft right now.
https://gocd.github.io/pr-review.gocd.org/pr-1394/releases

Prepare release notes for 22.2.0

---

source/analytics/index.html.erb
source/partials/release_notes/_release-17-8-0.md.erb
source/partials/release_notes/_release-17-9-0.md.erb
source/partials/release_notes/_release-19-2-0.md.erb
source/partials/release_notes/_release-20-5-0.md.erb
source/posts/2018-10-16-new-gocd-features.html.markdown.erb

Replace with the newer github repo references where possible.

Remove references to extensions-docs

---

data/plugins/notification_plugins.yml

Add go-gchat-notifier-plugin, see https://github.com/1and1/go-gchat-notifier-plugin

Add go-gchat-notifier-plugin

---

source/partials/release_notes/_release-23-4-0.md.erb

https://gocd.github.io/pr-review.gocd.org/pr-1544/releases/
See https://github.com/gocd/gocd/issues?page=1&q=milestone%3A%22Release+23.4.0%22+-author%3Adependabot%5Bbot%5D+sort%3Aupdated-desc

Add release notes for 23.4.0

---

source/partials/release_notes/_release-23-5-0.md.erb
source/posts/2023-02-13-gocd-project-status.html.markdown.erb

See https://github.com/gocd/gocd/issues?page=1&q=milestone%3A%22Release+23.5.0%22+-author%3Adependabot%5Bbot%5D+sort%3Aupdated-desc

Add release notes for 23.5.0

---

source/partials/release_notes/_release-24-1-0.md.erb

See https://github.com/gocd/gocd/issues?q=milestone%3A%22Release+24.1.0%22+-author%3Adependabot%5Bbot%5D+sort%3Aupdated-desc+

Add 24.1.0 release notes

---

source/partials/release_notes/_release-24-2-0.md.erb

https://github.com/gocd/gocd/issues?q=milestone%3A%22Release+24.2.0%22+-author%3Adependabot[bot]+sort%3Aupdated-desc+

Add 24.2.0 release notes

---

.github/workflows/build_and_preview.yml
.github/workflows/publish.yml

Using IAM Role with GHA OIDC provider to get the AWS Credentials for syncing with S3 bucket.

Using GHA OIDC IAM role to sync the artifacts with S3 bucket.

---

data/plugins/secrets_plugins.yml

Add [gocd-infisical-secrets-plugin](https://github.com/riebecj/gocd-infisical-secrets-plugin).

Adding Infisical Secrets Plugin
