gocd/www.go.cd

index.html

I thought it would be useful in the main Read Documentation link on the Go homepage pointed at the actual site rather than the GitHub documentation project, as it is easier to use and the proper link is hard to find otherwise.

Homepage Read Docs link now links to user docs site

---

_includes/header.html

Allow the root of the navigation bar to have target="_blank" set. Earlier, that attribute was not used. Was allowed only in the second level.

Allow target in root of nav bar

---

community/plugins.html

Created a Notification plugins section, and added slack build notifier plugin to the list.

Adding Slack build notifier plugin to the list

---

_config.yml

GitHub pages warns about it being incorrect.

Remove highlighter from _config.yml.

---

community/events.markdown

This page had not been maintained since last summer. This gave the very incorrect impression that we hadn't taken part in any events. Decided to remove the past events section since nothing there pointed to archived content anyway.

Decided to remove old events

---

_config.yml
css/main.css
download/index.html
index.html
subscribe.html

We've heard quite often that people using Go don't know when a new release comes out. Since we don't require any information to download, there hasn't been a way other than social networks to share this information. 
We've created a program in our marketing system that will allow us to update people on important news about Go. People subscribing for these updates will not be added to other marketing programs. 
We're still not requiring personal information to download, but now people will have a way to subscribe to updates if they want them.

Subscribe to updates link

---

_config.yml

The resources are mostly about learning so this makes more sense. Some people are saying they don't know about the mailing lists and webinars.

moved resources to Learn More section

---

_config.yml
contribute/index.html

One was pointing to the previous release and another to a non-existent page
This now lands on the [milestone](https://github.com/gocd/gocd/milestones?direction=desc&sort=completeness&state=open) page so people could have a look at all open milestones sorted based on the completion status

Fixing links to roadmap

---

_data/task_plugins.yml

Hi,
I've made a small plugin for polling the application health endpoint till the application become operational, or fail the build after configured amount of seconds.
https://github.com/jmnarloch/gocd-health-check-plugin

gocd-health-check-plugin

---

css/main.css

This fixed the banner problem on safari. Not sure why the overflow was set.

Removing overflow on the div to fix problem on smaller screens

---

css/main.css

2-line titles on plugins or single-line descriptions caused the plugin grid to fall out of of square.
Before:
After:
We have two remaining issues though:
1. two-line "By"-lines
2. the "Contribute" square

Improve Plugins Grid formatting

---

community/plugins.html

In the words of my CSS friend, `all's fair in love and CSS, my friend`.
Before:
After:

Correct the Grid for the Contribute plugins.

---

css/responsive.css
css/rwdgrid.css

Here is an accidental change (a1b829ad34753ed814fc7c6f2b5700ecd2481701) to css grid library 'rwdgrid.css', which cause couple place using grid broken.  For example: https://www.go.cd/contribute/contribution-guide.html.
This PR revert that change.  It also reduced the navigation bar padding to compensate the grid margin added while grid system is really working

fix the broken grid system

---

_includes/analytics.html
_includes/header.html
_includes/releaseAnnouncement.html
_includes/social-icons.html
_layouts/default.html
_layouts/home.html
css/main.css
download/index.html
index.html
js/download.js

This PR add anonymous visitor tracking for go.cd website using https://www.journey-app.io.
With usage data captured, we can potentially gain more understanding how user use the website and how they come. Thus provide us better information when we want to:  drive more traffic, increase adoption (downloads), or generally improve user experience of the website.
Current actions tracked in this PR are:
"open /foo page":  visitor open any pages;
"click foo>bar menuitem": visitor click menu items on the navigation header;
"agent download":  visitor download agent installer.
"server download":  visitor download server installer;
"click download-* tab":  visitor switching between different OS on download list page
"click github-fork-me button":   visitor click the "github fork me" stripe
"click …

Add journey-app integeration to track vistor actions anonymously

---

source/partners.html.erb
source/plugins.html.erb
source/posts/2014-02-24-how-peg-your-pipeline-dependency-version.html.markdown.erb
source/posts/2014-05-18-manage-agents-with-docker.html.markdown.erb
source/posts/2014-08-19-cloning-templates.html.markdown.erb
source/posts/2015-04-27-Feature-Branch-Support.html.markdown.erb
source/posts/2015-05-06-Getting-Started-Resources.html.markdown.erb
source/posts/2015-06-18-authentication-end-point.html.markdown.erb
source/posts/2015-06-18-plugin-settings.html.markdown.erb
source/posts/2015-07-07-GitHub-Integration.html.markdown.erb
source/posts/2015-12-22-gocd-in-2016.html.markdown.erb
source/posts/2015-12-28-gocd-continuous-delivery-through-pipelines.html.markdown.erb
source/posts/2016-02-08-not-done-unless-its-done-security.html.markdown.erb
source/releases.html.erb

* www.go.cd/documentation/user => docs.go.cd
* www.go.cd/documentation/developer => developer.go.cd/current

Fix all documentation urls

---

data/repo_plugins.yml

This plugin is build on the _Maven (Nexus) repository poller_ already listed in the plugins section. I made quite a few changes so that it is now better suited for our use cases (e.g. use of Nexus and Artifactory repositories).

Added new Maven repo plugin

---

config.rb

Previously, it would only show PRs, which sometimes are less clear
than the corresponding issue.
Now all issues are shown, which includes PRs.
Please note that no filter for `is:closed` was added, as all
issues in a milestone are always closed. That way, the filter
is simpler.
Fixes #327

Link to changelog includes all milestone issues

---

source/partials/release_notes/_release-16-9-0.html.erb

Hi, the release notes seem to contain a duplicate paragraph on deprecated "Task plugins"

removed a duplicate paragraph in latest release notes

---

source/download.html.erb

Use the browser to approximate the installer tab to be selected by default.

Detect user os and default to the corresponding installers

---

source/partials/next_release/_release.md.erb
source/partials/release_notes/_release-16-12-0.md.erb

Removed them from the next release's release notes as well, since they should work. Should we warn that they need to be upgraded?

Update plugins which have been upgraded

---

source/plugins.html.erb

Navigate to plugin tab using url#tab 
- http://www.gocd.io/plugins#scm-plugins will open SCM plugin tab
Fixed select tab based on index. 
- http://www.gocd.io/plugins#tab-index will also open respective tab

Added support for plugin tab navigation through #url

---

data/notification_plugins.yml

Hello, I've made the following plugin, can you add it to the GoCD's plugins page?
https://github.com/gmazzo/gocd-build-watcher-plugin
Regards

Add my plugin to https://www.gocd.io/plugins/

---

data/repo_plugins.yml

* They seem abandoned
* Or, at least, they have not been updated to work with 17.x

Remove some plugins which no longer work

---

data/auth_plugins.yml

The TLS client certificate plugin has been migrated to use the new authorization API.

Remove TLS cert plugin from authentication plugin list

---

source/assets/javascripts/app/_download_new.js
source/assets/javascripts/app/_tabs.js
source/assets/stylesheets/scss/_downloads_new.scss
source/cloud.html.erb
source/download.html.erb
source/download_new.html.erb
source/next-release.html.erb
source/plugins.html.erb
source/releases.html.erb

Will squash merge.
* Stop depending on click events generated using jQuery for everything.
* Small formatting and color changes (asked by Emily).
* Fix sorting of AMI versions.
* Show loading indicator when downloading.
* Cache downloaded JSON. Don't keep downloading during every click.
* Remove "Archive" tab. Old releases will show everything now.
* Fix bug of content going away when switching OSes.
* Simplify some tab-related code.

Improvements to the new downloads page

---

source/assets/javascripts/app/_download_new.js
source/assets/javascripts/app/_tabs.js
source/assets/stylesheets/scss/_plugins.scss
source/download_new.html.erb
source/plugins.html.erb
source/releases.html.erb

- Show tab name in URL bar (Click on a tab, check URL bar)
- Can go directly to packages for an OS (`/downloads_new#debian`)
- Use proper tab names on plugin page (`/plugins#elastic-agents`)
- Docker images tab: Links are now clickable
- Async marketo code (not necessarily about tabs, I know, sorry)

Tab improvements

---

source/assets/javascripts/app/_download_new.js

* Since we support only the last 12 releases made, showing all the releases might prompt some users to download unsupported versions.
* Users asking for old releases are very rare. We can find the path from releases.json for such cases.
* Also, feedback from @maheshp was that it seemed like a lot of boxes to show. 
@arvindsv - thought about providing a `showAll=true` option in the url but decided against it. But, I can add it if you can tell me whether the frequency of these requests for old releases is high.

Show only the last 12 releases made.

---

data/notification_plugins.yml

Added Cisco Spark build notifier plugin to the notification plugins page

Add t04glovern/gocd-spark-build-notifier to listing.

---

data/authorization_plugins.yml

This is adding the [Okta OAuth authorization plugin](https://github.com/szamfirov/gocd-okta-oauth-authorization-plugin) in the **plugins** section of the website.

Adding Okta OAuth authorization plugin

---

source/assets/stylesheets/scss/_navigation.scss
source/partials/_header.erb

The target should also open in the current window, as opposed to a new tab.

Documentation top-level navlink needs a current-page indicator

---

source/events.html.erb

"Get tickets" didn't make sense in the context of all the events in this section, changing to "Register"

updated get tix to register

---

source/assets/javascripts/marketo_popover.js
source/download.html.erb
source/enterprise-campaign/index.html.erb
source/enterprise/contact.html.erb
source/enterprise/support.html.erb
source/partials/_post-page_subscribe_to_blog.html.erb
source/partials/_subscribe_to_blog.html.erb
source/sales-sign-up.html.erb
source/subscribe.html.erb

- Swapped script load order to satisfy dependencies
- marketo_popover.js now holds all marketo fallback logic
- Special message for Firefox users as there is built-in tracker blocking

Ensure marketo load error message displays when load fails for any reason

---

source/assets/javascripts/marketo_popover.js

Chrome also uses the words "mozilla" and "gecko" in its user agent string...

Firefox detection needs to be narrower

---

source/partials/release_notes/_release-18-5-0.md.erb

IMPORTANT: This publishes the notes to releases page, not `next-release` so merge only if this looks ok.

Release notes for 18.5

---

data/plugins/artifact_plugins.yml
data/plugins/authorization_plugins.yml
data/plugins/elastic_agent_plugins.yml

The current download link for the plugin is broken.
Edit: Also piggybacking another couple of URL changes with this PR -- the URL for the pricing link is updated.

Add missing releases URL for Docker Registry Artifact Plugin

---

source/assets/javascripts/app/_getting_started.js
source/assets/stylesheets/scss/_getting-started.scss

I moved the caret for the introduction to GoCD dropdown to the link (vs the li) since the click handler is on the link (not the li). This way when you click on the caret itself the menu will expand or collapse which is intuitive and the behavior I would expect. 
I also changed the behavior of the collapsing to allow multiple sections ("Parts") to be open simultaneously.

Updates to the getting started dropdown

---

source/download.html.erb

Related to https://github.com/gocd/gocd-cloud/pull/10
Now that https://github.com/gocd/gocd-cloud/pull/10 adds demo AMIs to two regions (potentially), there needs to be a dropdown to show the AMIs across regions.
Can be merged before https://github.com/gocd/gocd-cloud/pull/10.

Show demo AMIs from multiple regions

---

source/assets/javascripts/app/_main.js
source/assets/stylesheets/enterprise/_utilities.scss
source/enterprise/thoughtworks-go-extensions-eula.html.erb
source/enterprise/thoughtworks-support-services-general-terms.html.erb

Because the assets for the microsite (www.thoughtworks.com/go) are missing, the CSS and images for the terms and eula pages are now broken. 
We've decided to redirect requests from www.thoughtworks.com/go/thoughtworks-go-extensions-eula to www.gocd.org/enterprise/thoughtworks-go-extensions-eula and www.thoughtworks.com/go/thoughtworks-support-services-general-terms to www.gocd.org/enterprise/thoughtworks-support-services-general-terms. 
Per Jeremy's request, we'd like to show a notice when the pages have been redirected. This PR gives us the option to do that using ?redirected=true

Added notice to eula and general terms pages if they include '?redirected=true'

---

data/plugins/task_plugins.yml

Fixes a more or less broken link (currently the link points to an empty wiki page) to the Haufe-Lexware Docker-Pipeline-Plugin.
I checked the other plugins-related links. They are fine.
Maybe the PR is too trivial – so, feel free to reject it.

Fixes a broken link to Docker-Pipeline-Plugin

---

README.md
source/partials/next_release/_release.md.erb
source/partials/release_notes/_release-19-4-0.md.erb

Trying to be more clear in release notes, about supported Java versions.
See image in [comment below](https://github.com/gocd/www.go.cd/pull/987#issuecomment-497673267).

Add Java versions to release notes

---

source/download.html.erb

It's unlikely that it's being used much. No point keeping them around. Plan to "hard remove" on or around Aug 1.

Soft remove AMIs

---

data/plugins/task_plugins.yml

Here is the dunner task plugin: https://github.com/leopardslab/dunner-gocd-plugin to execute docker tasks using dunner.
With more features coming up in Dunner, it ll enable users to run and manage docker tasks easily. Even if task execution fails through Go, it gives way to run them manually using the generated config file.

Add Dunner task plugin

---

source/posts/2019-06-25-GoCD-non-root-containers.html.markdown.erb

This needs to be merged at the time of `19.6.0` release

Publish non root container blog post from draft to public

---

source/partials/release_notes/_release-19-6-0.md.erb

Add elastic agent extension v4 deprecation notice in 19.6.0 release notes

---

source/assets/javascripts/app/_test_drive_download.js

IE lacks the `URL` constructor, and in this case, it's not necessary. It was there just to sanitize the URL, but it's constructed quite carefully anyway.

Fix Test Drive download to be compatible with legacy browsers, namely IE.

---

source/assets/javascripts/app/_download.js
source/partials/release_notes/_release-20-5-0.md.erb

- Clarify that data migration is needed even if you decide not to move to PostgreSQL.
- Also: Remove the weekday from the release date in the downloads page.

Clarify a part of the release notes

---

source/assets/javascripts/app/_download.js
source/download.html.erb

Issue: #1136 
Added an experimental docker images section which points to `gocdexperimental/{image_name}`
P.S. - the weird title is go around the mergeable check

Show an ex_perimental docker images section

---

source/download.html.erb
source/kubernetes/index.html.erb
source/posts/2018-03-21-continuous-delivery-gocd-kubernetes.html.markdown.erb
source/posts/2018-10-16-new-gocd-features.html.markdown.erb
source/posts/2019-05-14-installing-configuring-gocd-gke-using-helm.html.markdown.erb
source/posts/2019-09-17-configure-gocd-agents-kubernetes-static-elastic.html.markdown.erb
source/posts/2020-04-14-gocd-on-kubernetes-using-terraform.html.markdown.erb

* Use GoCD Helm Chart repository instead.
* Change docs to use gocd/gocd instead of stable/gocd.
* Point to hub.helm.sh gocd helm chart.
* Fix various links pointing to charts yaml from stable/gocd.

Use Offical GoCD Helm Chart link

---

data/plugins/authorization_plugins.yml

I've create an Keycloak authorization plugin based on Okta plugin, If it has a quality to get presented on plugin page it can help someone that use Keycloak Authorization Server.

Add Keycloak plugin authorization

---

data/plugins/scm_plugins.yml

Developed a new SCM plugin to integrate the GoCD server pipeline with FTP server to download all source codes, this plugin helps when there is no access to Git in deployment environment or when you want to package source code along with containers in production environment to protect IP/License/Copy rights

Adding new SCM plugin "gocd-ftp-server-plugin" on the plugin pages

---

data/plugins/config_repo_plugins.yml

It seems like https://github.com/ketan/gocd-groovy-dsl-config-plugin is not actively maintained.
-> Switch to https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin
@ketan I hope it's fine with you.

plugins: update config repo groovy plugin urls

---

source/partials/release_notes/_release-21-3-0.md.erb
source/partials/release_notes/_release-21-4-0.md.erb

Prepared release notes as discussed.
- Milestone [without dependabot stuff](https://github.com/gocd/gocd/issues?page=2&q=milestone%3A%22Release+21.4.0%22+-author%3Aapp%2Fdependabot)
- [commits to current master](https://github.com/gocd/gocd/compare/21.3.0..f3b865c)
- [API changelog](https://api.gocd.org/21.4.0/#api-changelog)
- [plugin API changelog](https://plugin-api.gocd.org/21.4.0/#api-changelog)
Feel free to edit or critique at will :-)

Prepare 21.4.0 release notes

---

source/partials/release_notes/_release-21-4-0.md.erb

Add missing item to release notes for 21.4.0

Missed from release notes the switch to Debian slim for agent images

---

source/partials/release_notes/_release-22-3-0.md.erb

Hope to release some time shortly after Java `17.0.5` is released (next week or so), depending on other work going on.
https://github.com/gocd/gocd/issues?q=milestone%3A"Release+22.3.0"+sort%3Acreated-asc+-author%3Adependabot[bot]
https://gocd.github.io/pr-review.gocd.org/pr-1416/releases/

Release notes for 22.3.0

---

source/partials/release_notes/_release-23-2-0.md.erb

Preparing for release, see https://github.com/gocd/gocd/issues?page=1&q=milestone%3A%22Release+23.2.0%22+-author%3Adependabot%5Bbot%5D+sort%3Aupdated-desc

Add release notes for 23.2.0

---

Gemfile.lock

Revert "Bump concurrent-ruby from 1.3.4 to 1.3.5"

---

.github/workflows/build_and_preview.yml
.github/workflows/pr_workflow.yml
.github/workflows/publish.yml

This repo is too painful to manaage via GH pages; the actions usually fail due to race conditions and it's generally not worth the hassle. Easy to build a PR locally if there is risk; or just rely on preview.gocd.org from master.

Simplify workflows and remove PR-review previews
